/*
 * Ek hi jagah se saare icons.
 *
 * Website `react-icons/go` (GitHub Octicons) use karti hai — admin bhi wahi
 * set use karta hai taaki dono screens ek hi brand lagein. Yahan semantic naam
 * diye hain (Icons.approve, Icons.owner) taaki page files me Go* naam bikhre
 * na aur icon badalna ek line ka kaam rahe.
 */

import type { IconType } from "react-icons";
import {
  GoAlertFill,
  GoArrowRight,
  GoArrowUpRight,
  GoBell,
  GoBriefcase,
  GoCalendar,
  GoCheck,
  GoCheckCircleFill,
  GoChecklist,
  GoChevronDown,
  GoChevronRight,
  GoChevronUp,
  GoClock,
  GoCommentDiscussion,
  GoContainer,
  GoCreditCard,
  GoDatabase,
  GoDeviceMobile,
  GoDotFill,
  GoEye,
  GoEyeClosed,
  GoGear,
  GoGlobe,
  GoGoal,
  GoGraph,
  GoHistory,
  GoHomeFill,
  GoImage,
  GoInfo,
  GoKey,
  GoLightBulb,
  GoLinkExternal,
  GoLocation,
  GoMail,
  GoMegaphone,
  GoMilestone,
  GoOrganization,
  GoPackage,
  GoPencil,
  GoPeople,
  GoPerson,
  GoPersonAdd,
  GoPlus,
  GoRocket,
  GoSearch,
  GoServer,
  GoShieldCheck,
  GoShieldLock,
  GoSidebarExpand,
  GoSignOut,
  GoStack,
  GoStar,
  GoStarFill,
  GoSync,
  GoTag,
  GoTasklist,
  GoTrash,
  GoTrophy,
  GoUnverified,
  GoVerified,
  GoX,
  GoXCircleFill,
  GoZap,
} from "react-icons/go";

export type { IconType };

export const Icons = {
  /* navigation */
  dashboard: GoGraph,
  guide: GoLightBulb,
  listings: GoHomeFill,
  users: GoPeople,
  subscriptions: GoCreditCard,
  testimonials: GoStarFill,
  banners: GoImage,
  content: GoPencil,
  plans: GoTag,
  menu: GoSidebarExpand,
  logout: GoSignOut,

  /* actions */
  approve: GoCheckCircleFill,
  check: GoCheck,
  reject: GoXCircleFill,
  hide: GoEyeClosed,
  show: GoEye,
  edit: GoPencil,
  remove: GoTrash,
  add: GoPlus,
  search: GoSearch,
  filter: GoChecklist,
  refresh: GoSync,
  external: GoLinkExternal,
  arrow: GoArrowRight,
  arrowUp: GoArrowUpRight,
  chevronDown: GoChevronDown,
  chevronRight: GoChevronRight,
  moveUp: GoChevronUp,
  moveDown: GoChevronDown,
  close: GoX,

  /* status / meta */
  pending: GoClock,
  live: GoDotFill,
  alert: GoAlertFill,
  info: GoInfo,
  verified: GoVerified,
  unverified: GoUnverified,
  shield: GoShieldCheck,
  lock: GoShieldLock,
  key: GoKey,
  bell: GoBell,
  calendar: GoCalendar,
  history: GoHistory,
  target: GoGoal,
  trophy: GoTrophy,
  rocket: GoRocket,
  zap: GoZap,

  /* entities */
  owner: GoBriefcase,
  tenant: GoPerson,
  admin: GoShieldCheck,
  register: GoPersonAdd,
  organization: GoOrganization,
  phone: GoDeviceMobile,
  mail: GoMail,
  locality: GoLocation,
  globe: GoGlobe,
  server: GoServer,
  database: GoDatabase,
  feedback: GoCommentDiscussion,
  megaphone: GoMegaphone,
  milestone: GoMilestone,
  settings: GoGear,
  tasks: GoTasklist,
  star: GoStar,
  starFill: GoStarFill,

  /* property types */
  flat: GoOrganization,
  room: GoContainer,
  shop: GoPackage,
  pg: GoStack,
  land: GoMilestone,
} satisfies Record<string, IconType>;
